# Generated by Django 4.0.1 on 2022-01-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccesRecord',
            new_name='AccessRecord',
        ),
    ]
